"""remove price column

Revision ID: 37dd0c7597db
Revises: 6d4c6efccd24
Create Date: 2026-09-04 20:58:04.121944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37dd0c7597db'
down_revision: Union[str, Sequence[str], None] = '6d4c6efccd24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('price_rub', sa.Float(), nullable=False))
    op.add_column('games', sa.Column('price_kzt', sa.Float(), nullable=False))
    op.add_column('games', sa.Column('price_usd', sa.Float(), nullable=False))
    op.add_column('games', sa.Column('price_uah', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'price_uah')
    op.drop_column('games', 'price_usd')
    op.drop_column('games', 'price_kzt')
    op.drop_column('games', 'price_rub')
    # ### end Alembic commands ###
